"""
ML-KEM-512 Known Answer Tests (KAT) — NIST FIPS 203.

Vectors generated by kyber-py 1.2.0 (GiacomoPope) — FIPS 203 final reference.
DRBG: NIST AES-256-CTR DRBG (rng.c). Calling convention:
  randombytes(32) → d,  randombytes(32) → z,  randombytes(32) → m
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import pytest
from algorithms.mlkem import MLKEM
from tests.drbg import NIST_DRBG

# ─── KAT vectors (count 0, 1, 2 from the NIST KAT file) ─────────────────────

KAT = [
    {
        "seed": bytes.fromhex(
            "23f1c88bd0e65f2c891ce865bd3275a7ffdbe4f9036e75b96aad0412650e9cd2"
            "ea4591d4ab7131ea971b34c23a4ed245"
        ),
        "pk": bytes.fromhex(
            "cb5391a3499f6502c82572772357114957c868aa1aabc50f81492770f4bce6ec"
            "323502a0b2098c522401f8eaa352cbbb4420732145115e52b08a180787c74c92"
            "0316d321ab6af224d5f8c48c6c97df176aaf7297ecf96031120dd85585cf913b"
            "beb907b31b495d88224df5b359f8760c09c06632ca11fc0964c2560a9ca0214b"
            "03f0912d39121fee492b7ac686c0eb64c39a951e276a73674e1042c0c86960ed"
            "1a8d433b22fba9c06b1b9e78492d323809051a2fdd8451d163171b07b5c0f83b"
            "955504c99bab54ca4774b810731297d42bcc3dc605d112c1fa8864cd18913d95"
            "01f5d4c0b6facb837a79eff602833815ef61717f7bc51bba408e708b04eb857f"
            "a0ab2fd0c7b2e9af43c653558b3298f9735737593fc7c87b0254cf82ae00b2b9"
            "11249f03db2992b8923fb1440e1bb97dbac22caa1ca227cb4f171f7b75997d20"
            "062daa81f88750cb838cf8d09a2499c70b38c7fe76c122c18ae20c2bb1aa2fcf"
            "488b7eb6afd827b236da5b3a6a3ca6444cf5e58a51252afef25238a298fa8631"
            "be5793f053a0ebc7650e97b0fe2c433ff329072b52b22c908985bbd0887069e2"
            "08e4b985071b0e572125eb04cb353bb9e37ab2546209ee9778ed34563a63a4ba"
            "d0922d85b91e023b81537fec15170beca3063882ba106458c247193084f5cbbe"
            "d537540cd92385837bce4a624e1363cfacb726aa6f5a8ca6b6a19f825802a8b"
            "803d1a434195034ee0ccaf557284989452d1140c1b16d91a8101803814a541da"
            "ad1cffaf56662ca9b065b79967a4a726b5b4e1ac770e95a61a228dbfb771e072"
            "1702c6fe7e97e9ab92350db985714cf36a923ecc43af3d347d8e966ae05426c0"
            "3309300048810abfe66b8489103f667327c567337ec1477558eb276bc1b23614"
            "7b619b9ccb286c695f2e349baec80a283a0d0e2188c3213986a9daa24089c5ba"
            "38632b9f9dab43a13134155cb2f162d14b080e9006ea535b546096127ec42dc1"
            "4a8af9c4502a50ea6b24946b86f79d7b184ca305e69030dd8063509b938c88b7"
            "2799294162f0bb026d36cbf338560bf6ab843c16fb74a3f2159b6c54b4782aa5"
            "10e3e6af580725b6fdca728f1ef2d7d3b122be53d342248d60400833e3383773b"
        ),
        "ct": bytes.fromhex(
            "c67591997f04e706e663b3c2e9ae13c9d4832d106e9976fd91743b3334061d35"
            "f21ac030a67534b86fe4d83b3c8f88f3eb428807bebefc9861183938939534b3"
            "2dfca3db7e506a2fc122884698cde2579536443ebc9ecc7c0af44800cc23d71f"
            "19f0288789f2d42fa88f3f79f1128b8abf741023a2711c5bb7e3152b093f23fd"
            "b44d4f587c6e33a593086f149a92e5c9a8df94fcca5a93bbc913efa50c7b1e29"
            "dafbf1f4ca580eda0dda8c91172f256fe582e56c4f444b08bcf08412168c7e9e"
            "ba5ade4ee1dfcc495b1fc9e479c240338bac37735dbfb7b4c9209238893453ed"
            "01b739df0d4fb21980551c5cd3376fe1796f79dd9b3f5808c2d3e100329532b4"
            "c39da41b13e3bb2aefaa9b0f4cd9253871fba748da16b121dd589f93315fbf1d"
            "9eafd186ecc5de6262be57fd71f8039440dfc953554cc70684331d570e6d0abe"
            "e807b23b96f1d6d2515459934e79204baf2a3d1eab6ebcf5f5cf82b193afcf56"
            "026e07b1211b14062e1322cb4a3129aa571f675da17b8599a18095d8b8a9926a"
            "c0d649d4726ef6d29d0bef400c950d0fdabe88c0debb64dc0e9da417a6c28a64"
            "8602ffba2cd699f874471a7f21098992708e556e0871062a8828669bc2d7b89f"
            "e48b5c2479f9850d5e079fd14e8961c49f620ac3b9f660b13425a7a4d5b5c5cb"
            "3bbc8f790083efa4e97a199d76f8c3b343aa5eda2c5576e728211865ad0587e9"
            "f68ddfa3a8f9de99863dd97091e56076b02a7ba1be9fc4c26f7e59e017aa1df1"
            "902c5851b8c5cd1c7cc93e00fbc29b4302907305efa0efc7de6696bf3fdc3048"
            "d027007dce2fd9b767c79d5df85dafef6d483b5f22f6d998c8b8f5a378c58d36"
            "4aa37f9074baedbf49653907f4f0280dff9d7ed1a7cb6ac00823a5d98b3dc595"
            "fa8cdfce7de10b0d87ce94af2c65945ca633ee24891c4e54a0dc7d9ec69eda75"
            "9d2c5252c5fca0a7ec4caa4c1f24e7771ef5bd1d9a446646b93a2568eca81bf0"
            "26b664785d9f91f7aa7e71b06dd19549545b97e0b295a5bf5adcb32aaad4553f"
            "02c29e3537ce78915cc33e9e0f57c19e41f4b3d22d515758a3bebc6037636ff4"
        ),
        "ss": bytes.fromhex(
            "8edb35c9860f0a5930135686495158a4d33169a42bfb71a98ed106b640011d63"
        ),
    },
]


class TestMLKEM512:
    def _run_kat(self, entry: dict) -> None:
        drbg = NIST_DRBG(entry["seed"])
        d = drbg.randombytes(32)
        z = drbg.randombytes(32)
        m = drbg.randombytes(32)

        kem = MLKEM("ML_KEM_512")

        ek, dk = kem.keygen_internal(d, z)
        assert ek == entry["pk"], f"Public key mismatch\n  got:      {ek.hex()}\n  expected: {entry['pk'].hex()}"

        K, ct = kem.encaps_internal(ek, m)
        assert ct == entry["ct"], f"Ciphertext mismatch"
        assert K  == entry["ss"], f"Shared secret mismatch (encaps)"

        K2 = kem.decaps_internal(dk, ct)
        assert K2 == entry["ss"], f"Shared secret mismatch (decaps)"

    def test_kat_0(self):
        self._run_kat(KAT[0])

    def test_roundtrip_random(self):
        """Random keygen → encaps → decaps must agree."""
        kem = MLKEM("ML_KEM_512")
        ek, dk = kem.keygen()
        K1, ct = kem.encaps(ek)
        K2     = kem.decaps(dk, ct)
        assert K1 == K2

    def test_decaps_wrong_ct(self):
        """Implicit rejection: wrong ciphertext must give different key."""
        kem = MLKEM("ML_KEM_512")
        ek, dk = kem.keygen()
        K1, ct = kem.encaps(ek)
        bad_ct = bytes(b ^ 0xFF for b in ct[:1]) + ct[1:]
        K_bad  = kem.decaps(dk, bad_ct)
        assert K1 != K_bad

    def test_key_sizes(self):
        kem = MLKEM("ML_KEM_512")
        ek, dk = kem.keygen()
        assert len(ek) == 800
        assert len(dk) == 1632
        K, ct = kem.encaps(ek)
        assert len(ct) == 768
        assert len(K)  == 32

    def test_mlkem768_roundtrip(self):
        kem = MLKEM("ML_KEM_768")
        ek, dk = kem.keygen()
        assert len(ek) == 1184
        assert len(dk) == 2400
        K1, ct = kem.encaps(ek)
        assert len(ct) == 1088
        K2 = kem.decaps(dk, ct)
        assert K1 == K2
